name: Client Prototype CD

on:
  push:
    branches: [ main ]

jobs:
  build-jar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven
        
    - name: Build JAR
      run: mvn clean package
      
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: labyrinth-client-prototype
        path: target/*.jar
        retention-days: 30
